type Query {
  viewer: User!
}

type Mutation {
  updateUser(userId: ID!, name: String, avatarUrl: String): User!
  addFriend(friendId: String!): User!
  removeFriend(friendId: String!): Boolean!
  createRoom(name: String!, friendIds: [String!]!): Room!
  removeRoom(roomId: String!): Room!
  createChat(roomId: String!, message: String!): Chat!
  removeChat(chatId: String!): Chat!
}

type User {
  userId: ID!
  name: String!
  email: String!
  avatarUrl: String
  friends: [User]!
  rooms: [Room]!
}

type Room {
  roomId: ID!
  name: String!
  users: [User!]!
  chats: [Chat]!
}

type Chat {
  chatId: ID!
  userId: ID!
  createdAt: String!
  message: String!
}
